//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadClient.DownloadServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DownloadServiceReference.IDownloadService")]
    public interface IDownloadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownloadService/GetFileSize", ReplyAction="http://tempuri.org/IDownloadService/GetFileSizeResponse")]
        long GetFileSize(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownloadService/GetFileSize", ReplyAction="http://tempuri.org/IDownloadService/GetFileSizeResponse")]
        System.Threading.Tasks.Task<long> GetFileSizeAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownloadService/DownloadFile", ReplyAction="http://tempuri.org/IDownloadService/DownloadFileResponse")]
        System.IO.Stream DownloadFile(string path, long startPosition, int length);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownloadService/DownloadFile", ReplyAction="http://tempuri.org/IDownloadService/DownloadFileResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> DownloadFileAsync(string path, long startPosition, int length);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDownloadServiceChannel : DownloadClient.DownloadServiceReference.IDownloadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DownloadServiceClient : System.ServiceModel.ClientBase<DownloadClient.DownloadServiceReference.IDownloadService>, DownloadClient.DownloadServiceReference.IDownloadService {
        
        public DownloadServiceClient() {
        }
        
        public DownloadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DownloadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DownloadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DownloadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long GetFileSize(string path) {
            return base.Channel.GetFileSize(path);
        }
        
        public System.Threading.Tasks.Task<long> GetFileSizeAsync(string path) {
            return base.Channel.GetFileSizeAsync(path);
        }
        
        public System.IO.Stream DownloadFile(string path, long startPosition, int length) {
            return base.Channel.DownloadFile(path, startPosition, length);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> DownloadFileAsync(string path, long startPosition, int length) {
            return base.Channel.DownloadFileAsync(path, startPosition, length);
        }
    }
}
